apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: kube-system
spec:
  timeout: 3m
  interval: 10m
  releaseName: cert-manager
  targetNamespace: kube-system
  chart:
    spec:
      chart: sealed-secrets
      version: "2.1.5"
      sourceRef:
        kind: HelmRepository
        name: bitnami-sealed-secrets
        namespace: kube-system
      interval: 40m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace

