apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  k8s-app: policy

bases:
  - github.com/open-policy-agent/gatekeeper-library/library/general

# Issue: using app-of-apps pattern and orchestrating synchronization using sync waves
# resources:
#   - constraints/cluster-constraints.yaml

namespace: gatekeeper-system