apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  timeout: 3m
  interval: 10m
  releaseName: cert-manager
  targetNamespace: cert-manager
  chart:
    spec:
      chart: cert-manager
      version: "v1.8.0"
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: cert-manager
      interval: 40m
      valuesFiles:
        - values.yaml
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace

