apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  k8s-app: loki

namespace: monitoring

resources:
  - namespace.yaml
  - ingress.yaml

helmCharts:
  - name: loki-stack
    repo: https://grafana.github.io/helm-charts/
    version: 2.5.0
    releaseName: loki-stack
    namespace: monitoring
    valuesFile: values.yaml
