apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  k8s-app: cert-manager

resources:
  - namespace.yaml
  - https://github.com/cert-manager/cert-manager/releases/download/v1.8.0/cert-manager.crds.yaml

helmCharts:
  - name: cert-manager
    repo: https://charts.jetstack.io
    version: v1.8.0
    releaseName: cert-manager
    namespace: cert-manager

namespace: cert-manager