apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  k8s-app: gatekeeper

resources:
  - https://raw.githubusercontent.com/open-policy-agent/gatekeeper/release-3.7/deploy/gatekeeper.yaml

  # OPA Gatekeeper Library
  - github.com/open-policy-agent/gatekeeper-library/library/general

  - constraints.yaml

