apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  k8s-app: ingress-nginx

resources:
  - https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.1.1/deploy/static/provider/cloud/deploy.yaml
  - helm-repository.yaml
  
patchesStrategicMerge:
  - CVE-2021-25742-configmap.yaml
