apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
  namespace: argocd
spec:
  project: default
  source:
    path: apps
    repoURL: 'http://172.18.0.2:32322/gitea_admin/k8s-gitops.git'
    targetRevision: main
  destination:
    namespace: gitops
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
