apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops
spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: gitops/apps
    repoURL: 'http://172.18.0.2:32322/gitea_admin/k8s-gitops.git'
    targetRevision: main
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
