apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gatekeeper-system

commonLabels:
  k8s-app: gatekeeper

resources:
  - https://raw.githubusercontent.com/open-policy-agent/gatekeeper/release-3.7/deploy/gatekeeper.yaml

  # Gatekeeper Policy Manager (GPM)
  - github.com/sighupio/gatekeeper-policy-manager?ref=v0.5.1

  - ingress.yaml