---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: linkerd
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./gitops/flux/runtime/source/linkerd
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops
  validation: client
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: linkerd
      namespace: linkerd
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: linkerd-viz
  namespace: flux-system
spec:
  dependsOn:
  - name: linkerd
  interval: 10m0s
  path: ./gitops/flux/runtime/source/linkerd-viz
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops
  validation: client
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: linkerd-viz
      namespace: linkerd-viz
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  dependsOn:
  - name: linkerd
  interval: 3m0s
  path: ./gitops/flux/runtime/source/cert-manager
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops
  validation: client
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: cert-manager
      namespace: cert-manager
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
# kind: Kustomization
# metadata:
#   name: sealed-secrets
#   namespace: flux-system
# spec:
#   dependsOn:
#   - name: linkerd
#   interval: 3m0s
#   path: ./gitops/flux/runtime/source/sealed-secrets
#   prune: true
#   sourceRef:
#     kind: GitRepository
#     name: gitops
#   validation: client
#   healthChecks:
#     - apiVersion: helm.toolkit.fluxcd.io/v2beta1
#       kind: HelmRelease
#       name: sealed-secrets
#       namespace: kube-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: metallb
  namespace: flux-system
spec:
  dependsOn:
  - name: linkerd
  interval: 3m0s
  path: ./gitops/flux/runtime/source/metallb
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops
  validation: client
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: controller
      namespace: metallb-system
    - apiVersion: apps/v1
      kind: DaemonSet
      name: speaker
      namespace: metallb-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  dependsOn:
  - name: metallb
  interval: 3m0s
  path: ./gitops/flux/runtime/source/ingress-nginx
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops
  validation: client
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: ingress-nginx
      namespace: ingress-nginx
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: finalizers
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./gitops/flux/runtime/source/finalizers
  dependsOn:
    - name: linkerd-viz
    - name: cert-manager
    - name: metallb
    - name: ingress-nginx
    # - name: sealed-secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops
  validation: client