apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: gitops
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: fluxcd
  url: https://github.com/kevinobee/flux-gitops