apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - metallb
  - ingress-nginx
  - argocd
  - gatekeeper
  - sealed-secrets
  - k8s-dashboard
  - loki

patches:
- path: policy/image_pull_policy_patch.json
  target:
    group: apps
    version: v1
    kind: Deployment
- path: policy/image_pull_policy_patch.json
  target:
    group: batch
    version: v1
    kind: Job
- path: policy/image_pull_policy_patch.json
  target:
    group: apps
    version: v1
    kind: DaemonSet
