apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
spec:
  project: dev
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 2.5.11
    chart: metallb
  destination:
    namespace: metallb-system
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
