apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: heimdall
  namespace: heimdall
spec:
  ingressClassName: nginx
  rules:
  - host: apps.example.com
    http:
      paths:
      - backend:
          service:
            name: heimdall
            port:
              number: 80
        path: /
        pathType: Prefix
