apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: sealed-secrets
    repoURL: https://bitnami-labs.github.io/sealed-secrets

---

apiVersion: v1
kind: Secret
metadata:
  name: sealed-secrets
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: sealed-secrets
  url: https://bitnami-labs.github.io/sealed-secrets
  type: helm
