name: Dynamic Analysis - Argo CD App of Apps

on:

  workflow_dispatch:

jobs:

  run-test:
    name: Argo CD App of Apps
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Create Kind cluster and setup GitOps
      run: |
        ./install.sh

    - name: Run Port Forward for Argo CD API server to localhost:8080
      run: |
        kubectl port-forward svc/argocd-server -n argocd 8080:443 &

    - name: Login to Argo CD using the CLI
      run: |
        pwd=$(kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d; echo)
        argocd login localhost:8080 --insecure --username admin --password ${pwd}

    - name: Get Argo CD Applications
      run: |
        argocd app get gitops
        argocd app sync gitops
        argocd app wait gitops
        argocd app list
