name: Dynamic Analysis - Argo CD App of Apps

on:
  push:
    branches: [ main ]
    paths:
      - 'apps/**'
      - 'gitops/**'

  pull_request:
    branches: [ main ]
    paths:
      - 'apps/**'
      - 'gitops/**'

  workflow_dispatch:

jobs:

  run-test:
    name: Argo CD App of Apps
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Run install script
      run: |
        ./install.sh

    - name: Wait for GitOps to be Healthy
      run: |
        argocd app wait gitops --health

    - name: Docker network checks
      run: |
        docker network inspect -f '{{.IPAM.Config}}' kind

    - name: Check Audit logging
      run: |
        logCount1=$(docker exec kind-control-plane cat /var/log/kubernetes/kube-apiserver-audit.log | wc -l)
        sleep 1s
        logCount2=$(docker exec kind-control-plane cat /var/log/kubernetes/kube-apiserver-audit.log | wc -l)
        if [ $logCount1 -eq $logCount2 ]; then exit 1 ; fi
