name: Dynamic Analysis

on:

  # push:
  #   branches: [ main ]
  #   paths:
  #     - 'apps/**'

  # pull_request:
  #   branches: [ main ]
  #   paths:
  #     - 'apps/**'

  workflow_dispatch:

jobs:

  test-applications:
    name: Applications available
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Run install script
      run: |
        ./install.sh

    - name: Docker network checks
      run: |
        docker network inspect -f '{{.IPAM.Config}}' kind

    - name: Check Audit logging
      run: |
        logCount1=$(docker exec kind-control-plane cat /var/log/kubernetes/kube-apiserver-audit.log | wc -l)
        sleep 1s
        logCount2=$(docker exec kind-control-plane cat /var/log/kubernetes/kube-apiserver-audit.log | wc -l)
        if [ $logCount1 -eq $logCount2 ]; then exit 1 ; fi
