name: Kubescape

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  nsa-security-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Kubescape
        run: curl -s https://raw.githubusercontent.com/armosec/kubescape/master/install.sh | /bin/bash

      - name: Scan YAML files in apps folder
        run: kubescape scan framework nsa,mitre,armobest apps/*.yaml