name: Kubescape

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  nsa-security-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Kubescape
        run: curl -s https://raw.githubusercontent.com/armosec/kubescape/master/install.sh | /bin/bash

      - name: Install Kustomize
        run: curl -s https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh | bash

      - name: Scan Argo CD Application files
        run: kustomize build apps | kubescape scan framework nsa -

      - name: Scan Argo CD YAML
        run: kustomize build applications/argo-cd | kubescape scan framework nsa -
