name: Kustomize Build Action

on:
  workflow_dispatch:

jobs:
  Kustomize-Build:
    runs-on: ubuntu-latest
    steps:

      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Kustomize build
        uses: ./.github/actions/kustomize-build
        with:
          build-path: '.'
          output-file: 'kustomize.yaml'
          upload-artifact-name: 'kustomize'

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
