name: Snyk Infrastructure as Code

on:
  schedule:
    - cron: '0 0 * * *'  # every day at midnight

  workflow_dispatch:

jobs:

  kustomize:
    name: Kustomize YAML
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate kustomize YAML
        run: kubectl kustomize --enable-helm apps > kustomize.yaml

      - name: Upload Kustomize YAML
        uses: actions/upload-artifact@v2
        with:
          name: kustomize
          path: kustomize.yaml

  snyk:
    name: Snyk Infrastructure as Code
    needs: kustomize
    runs-on: ubuntu-latest
    steps:
      - name: Download Kustomize YAML
        uses: actions/download-artifact@v2
        with:
          name: kustomize

      - name: Run Snyk to check configuration files for security issues
        continue-on-error: true
        uses: snyk/actions/iac@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          file: kustomize.yaml

      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: snyk.sarif
