name: Static Analysis

on:
  # push:
  #   branches: [ main ]
  #   paths-ignore:
  #     - '.github/**'

  # pull_request:
  #   branches: [ main ]
  #   paths-ignore:
  #     - '.github/**'

  # schedule:
  #   - cron: '43 3 * * 1'

  workflow_dispatch:

jobs:

  kustomize:
    name: Kustomize Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Kustomize Build
        uses: karancode/kustomize-github-action@master
        with:
          kustomize_version: '3.0.0'
          kustomize_build_dir: '.'
          kustomize_output_file: "kustomize.yaml"
          kustomize_build_options: "--load_restrictor none"
          enable_alpha_plugins: true

      - name: Upload Kustomize YAML
        uses: actions/upload-artifact@v2
        with:
          name: kustomize
          path: kustomize.yaml

  snyk:
    name: Snyk Infrastructure as Code
    needs: kustomize
    runs-on: ubuntu-latest
    steps:
      - name: Download kustomize build YAML
        uses: actions/download-artifact@v2
        with:
          name: kustomize

      - name: Run Snyk to check configuration files for security issues
        continue-on-error: true
        uses: snyk/actions/iac@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          file: kustomize.yaml

      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: snyk.sarif

  kubescape:
    name: Kubescape DevOps Best
    needs: kustomize
    runs-on: ubuntu-latest
    steps:
      - name: Install Kubescape
        run: curl -s https://raw.githubusercontent.com/armosec/kubescape/master/install.sh | /bin/bash

      - name: Download kustomize build YAML
        uses: actions/download-artifact@v2
        with:
          name: kustomize

      - name: Run Kubescape
        run: kubescape scan framework devopsbest --exclude-namespaces kube-system,kube-public kustomize.yaml # --enable-host-scan --fail-threshold 0

  datree:
    name: Datree
    needs: kustomize
    runs-on: ubuntu-latest

    steps:
      - name: Install Datree
        run: curl https://get.datree.io | /bin/bash

      - name: Download kustomize build YAML
        uses: actions/download-artifact@v2
        with:
          name: kustomize

      - name: Run Datree to check for Kubernetes misconfiguration issues
        run: datree test --schema-version 1.21.0 --ignore-missing-schemas kustomize.yaml || exit 0
