name: Test Cluster Applications

on:

  push:
    branches: [ main ]
    paths:
      - 'apps/**'

  pull_request:
    branches: [ main ]
    paths:
      - 'apps/**'

  workflow_dispatch:

jobs:

  test-integration:
    name: Test cluster applications
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-go@v1
      with:
        go-version: 1.13

    - name: Install latest version of Kind
      run: |
        GO111MODULE=on go get sigs.k8s.io/kind

    - name: Create Kind cluster
      run: |
        PATH=$(go env GOPATH)/bin:$PATH kind create cluster --config kind-config.yaml --wait 1m

    - name: Docker network checks
      run: |
        docker network inspect -f '{{.IPAM.Config}}' kind

    - name: Install Cluster applications
      run: |
        ./scripts/install-apps.sh

    - name: Audit logging checks
      run: |
        docker exec kind-control-plane cat /var/log/kubernetes/kube-apiserver-audit.log | wc -l
        sleep 1s
        docker exec kind-control-plane cat /var/log/kubernetes/kube-apiserver-audit.log | wc -l

    - name: Application ingress checks
      run: |
        ./scripts/test-apps.sh
