name: Trivy vulnerability scan

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'

  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'

  workflow_dispatch:

jobs:
  scan:
    name: Trivy vulnerability scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Trivy vulnerability scanner in IaC mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'
          format: 'sarif'
          output: 'trivy-iac-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        if: always()
        with:
          sarif_file: 'trivy-iac-results.sarif'
