apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  k8s-app: gitea

resources:
  - namespace.yaml

helmCharts:
  - name: gitea
    repo: https://dl.gitea.io/charts/
    version: 5.0.2
    releaseName: gitea
    namespace: gitea
    valuesFile: values.yaml

namespace: gitea