apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  k8s-app: argocd

namespace: argocd

resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.2.5/manifests/install.yaml
  - namespace.yaml
  - ingress.yaml

patchesStrategicMerge:
  - argocd-cm.yaml